(()=>{"use strict";
const engine=window.CalculatorEngine,storageApi=window.CalculatorStorage,store=storageApi.createStorage();
const MAX_HISTORY=storageApi.MAX_HISTORY||100,MAX_FAVORITES=storageApi.MAX_FAVORITES||50,defaults=storageApi.DEFAULT_SETTINGS,saved=store.loadSettings();
const settings={theme:["dark","light"].includes(saved.theme)?saved.theme:defaults.theme,style:["glass","classic","compact"].includes(saved.style)?saved.style:defaults.style,angleMode:["DEG","RAD"].includes(saved.angleMode)?saved.angleMode:defaults.angleMode,largeText:!!saved.largeText,sound:!!saved.sound,animations:saved.animations!==false};
const state={expression:"",result:"0",ans:"0",justCalculated:false,memory:0,history:store.loadHistory(),favorites:store.loadFavorites(),settings,panel:"history",search:""};
const q=s=>document.querySelector(s);
const refs={expr:q("#expression-display"),preview:q("#preview-display"),result:q("#result-display"),status:q("#status-message"),memory:q("#memory-indicator"),angleBadge:q("#angle-badge"),keypad:q("#keypad"),memoryButtons:q(".memory-buttons"),history:q("#history-list"),favorites:q("#favorites-list"),clearHistory:q("#clear-history"),historyMeta:q("#history-meta"),favoritesMeta:q("#favorites-meta"),search:q("#record-search"),tabs:[...document.querySelectorAll("[data-panel]")],panels:[...document.querySelectorAll("[data-panel-content]")],copy:q("#copy-result"),copyExpression:q("#copy-expression"),angle:q("#angle-mode"),theme:q("#theme-select"),style:q("#style-select"),large:q("#large-text"),sound:q("#sound-toggle"),animations:q("#animations-toggle"),reset:q("#reset-settings"),toast:q("#toast"),statsHistory:q("#stat-history"),statsFavorites:q("#stat-favorites"),statsMemory:q("#stat-memory"),statsAns:q("#stat-ans"),exportData:q("#export-data"),importData:q("#import-data"),importFile:q("#import-file"),help:q("#help-dialog"),helpButton:q("#help-button"),closeHelp:q("#close-help")};
function fmt(n){return String(n).replace(".",",")}
function display(exp){return exp.replaceAll("sqrt(","√(").replaceAll("sin(","sen(").replaceAll("*","×").replaceAll("/","÷").replaceAll("-","−")}
function toast(message){refs.toast.textContent=message;refs.toast.classList.add("is-visible");clearTimeout(toast.t);toast.t=setTimeout(()=>refs.toast.classList.remove("is-visible"),1800)}
function setStatus(message){refs.status.textContent=message||"";refs.status.classList.toggle("is-visible",!!message)}
function applySettings(){store.saveSettings(state.settings);document.body.dataset.theme=state.settings.theme;document.body.dataset.style=state.settings.style;document.body.classList.toggle("large-text",state.settings.largeText);document.body.classList.toggle("no-motion",!state.settings.animations);render()}
function renderPanels(){refs.tabs.forEach(t=>{const on=t.dataset.panel===state.panel;t.classList.toggle("is-active",on);t.setAttribute("aria-selected",String(on))});refs.panels.forEach(p=>p.hidden=p.dataset.panelContent!==state.panel)}
function previewValue(){if(!state.expression.trim())return null;try{return engine.evaluate(state.expression,{angleMode:state.settings.angleMode,ans:Number(state.ans)||0})}catch{return null}}
function render(){
 document.body.dataset.theme=state.settings.theme;document.body.dataset.style=state.settings.style;document.body.classList.toggle("large-text",state.settings.largeText);document.body.classList.toggle("no-motion",!state.settings.animations);
 const pv=previewValue();
 refs.expr.textContent=state.justCalculated?display(state.expression)+" =":display(state.expression)||"0";
 refs.preview.textContent=!state.justCalculated&&state.expression&&pv!==null?"≈ "+fmt(engine.formatResult(pv)):"";
 refs.result.textContent=fmt(state.result);refs.memory.hidden=Math.abs(state.memory)<1e-15;refs.angle.value=state.settings.angleMode;refs.angleBadge.textContent=state.settings.angleMode;
 refs.theme.value=state.settings.theme;refs.style.value=state.settings.style;refs.large.checked=state.settings.largeText;refs.sound.checked=state.settings.sound;refs.animations.checked=state.settings.animations;
 refs.statsHistory.textContent=String(state.history.length);refs.statsFavorites.textContent=String(state.favorites.length);refs.statsMemory.textContent=fmt(engine.formatResult(state.memory));refs.statsAns.textContent=fmt(state.ans);
 renderHistory();renderFavorites();renderPanels()
}
function clearAll(){state.expression="";state.result="0";state.justCalculated=false;setStatus("");render()}
function lastChar(){return state.expression.at(-1)||""}
function currentNumberHasDecimal(){const m=state.expression.match(/(?:^|[+\-*/^(])(-?(?:\d+(?:\.\d*)?|\.\d*))$/);return!!(m&&m[1].includes("."))}
function insert(text,kind){
 if(state.justCalculated){if(/^[+\-*/^]$/.test(text)||text==="%"||text==="!")state.expression=state.result;else{state.expression="";state.result="0"}state.justCalculated=false}
 if(kind==="function"){if(/[0-9.)A-Za-z]/.test(lastChar()))state.expression+="*";state.expression+=text+"(";setStatus("");render();return}
 if(kind==="constant"){if(/[0-9.)A-Za-z]/.test(lastChar()))state.expression+="*";state.expression+=text;render();return}
 if(text==="("){if(/[0-9.)]/.test(lastChar()))state.expression+="*";state.expression+="(";render();return}
 if(text===")"){let b=0;for(const c of state.expression){if(c==="(")b++;else if(c===")")b--}if(b<=0||/[+\-*/^(]$/.test(state.expression)){toast("Parênteses incompletos.");return}state.expression+=")";setStatus("");render();return}
 if(text==="!"||text==="%"){if(!state.expression||/[+\-*/^(]$/.test(state.expression)){toast("Digite um valor primeiro.");return}state.expression+=text;setStatus("");render();return}
 if(/^[+\-*/^]$/.test(text)){if(!state.expression){if(text==="-")state.expression="-";else{toast("Comece com um número.");return}}else if(/[+\-*/^]$/.test(state.expression)){if(text==="-"&&!state.expression.endsWith("-"))state.expression+="-";else state.expression=state.expression.slice(0,-1)+text}else state.expression+=text;setStatus("");render();return}
 if(/^\d$/.test(text)||text==="."){if(text==="."&&currentNumberHasDecimal())return;if(text==="."&&(!state.expression||/[+\-*/^(]$/.test(state.expression)))state.expression+="0.";else state.expression+=text;setStatus("");render()}
}
function toggleSign(){if(!state.expression)state.expression="-";else if(/^-?(?:\d+(?:\.\d*)?|\.\d+)$/.test(state.expression))state.expression=state.expression.startsWith("-")?state.expression.slice(1):"-"+state.expression;else if(state.expression.startsWith("-(")&&state.expression.endsWith(")"))state.expression=state.expression.slice(2,-1);else state.expression="-("+state.expression+")";state.justCalculated=false;render()}
function square(){if(state.expression)state.expression+="^2";state.justCalculated=false;render()}
function inverse(){state.expression=state.expression?"1/("+state.expression+")":"1/(";state.justCalculated=false;render()}
function insertAns(){insert("ans","constant")}
function calculate(){
 if(!state.expression.trim())return;
 try{const value=engine.evaluate(state.expression,{angleMode:state.settings.angleMode,ans:Number(state.ans)||0});const result=engine.formatResult(value);if(result==="Erro")throw new Error("Resultado inválido");addHistory(display(state.expression),result);state.result=result;state.ans=result;state.justCalculated=true;setStatus("");render();if(state.settings.sound)beep()}
 catch(err){state.result="Erro";state.justCalculated=true;setStatus(err instanceof Error?err.message:"Expressão inválida");render()}
}
function addHistory(expression,result){state.history.unshift({id:Date.now()+"-"+Math.random().toString(36).slice(2,7),expression,result,timestamp:Date.now(),angleMode:state.settings.angleMode});state.history=state.history.slice(0,MAX_HISTORY);store.saveHistory(state.history)}
function removeHistory(id){state.history=state.history.filter(x=>x.id!==id);store.saveHistory(state.history);render()}
function clearHistory(){if(!state.history.length)return;if(window.confirm("Limpar todo o histórico?")){state.history=[];store.clearHistory();render();toast("Histórico limpo.")}}
function favoriteExists(expression,result){return state.favorites.some(x=>x.expression===expression&&x.result===result)}
function toggleFavorite(expression,result){const i=state.favorites.findIndex(x=>x.expression===expression&&x.result===result);if(i>=0){state.favorites.splice(i,1);toast("Removido dos favoritos.")}else{if(state.favorites.length>=MAX_FAVORITES)state.favorites.pop();state.favorites.unshift({id:Date.now()+"-"+Math.random().toString(36).slice(2,7),expression,result,timestamp:Date.now()});toast("Adicionado aos favoritos.")}store.saveFavorites(state.favorites);render()}
async function copyText(value,label){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(String(value));else fallbackCopy(String(value));toast(label+" copiado.")}catch{toast("Não foi possível copiar.")}}
function fallbackCopy(value){const a=document.createElement("textarea");a.value=value;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}
function when(ts){try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(ts))}catch{return""}}
function filtered(list){const term=state.search.trim().toLowerCase();return term?list.filter(x=>(x.expression+" "+x.result).toLowerCase().includes(term)):list}
function record(item,allowDelete){
 const wrap=document.createElement("article");wrap.className="record";const main=document.createElement("button");main.type="button";main.className="record__main";main.dataset.expression=item.expression;main.dataset.result=item.result;
 const top=document.createElement("span");top.className="record__top";const ex=document.createElement("span");ex.className="record__expression";ex.textContent=item.expression;const time=document.createElement("time");time.textContent=when(item.timestamp);top.append(ex,time);const rs=document.createElement("strong");rs.className="record__result";rs.textContent=fmt(item.result);main.append(top,rs);wrap.append(main);
 const actions=document.createElement("div");actions.className="record__actions";const fav=document.createElement("button");fav.type="button";fav.className="icon-button";fav.dataset.action="favorite";fav.dataset.expression=item.expression;fav.dataset.result=item.result;fav.textContent=favoriteExists(item.expression,item.result)?"★":"☆";fav.setAttribute("aria-label",favoriteExists(item.expression,item.result)?"Remover favorito":"Adicionar favorito");
 const cp=document.createElement("button");cp.type="button";cp.className="icon-button";cp.dataset.action="copy";cp.dataset.result=item.result;cp.textContent="⧉";cp.setAttribute("aria-label","Copiar resultado");actions.append(fav,cp);
 if(allowDelete){const del=document.createElement("button");del.type="button";del.className="icon-button icon-button--danger";del.dataset.action="delete";del.dataset.id=item.id;del.textContent="×";del.setAttribute("aria-label","Excluir histórico");actions.append(del)}wrap.append(actions);return wrap
}
function renderRecords(listEl,metaEl,items,total,label,allowDelete){listEl.replaceChildren();metaEl.textContent=items.length===total?String(total)+" "+label:String(items.length)+" de "+String(total)+" "+label;if(!items.length){const e=document.createElement("div");e.className="empty-state";e.textContent=state.search?"Nenhum registro corresponde à busca.":label==="registros"?"Nenhum cálculo no histórico.":"Nenhuma expressão favorita.";listEl.append(e);return}items.forEach(x=>listEl.append(record(x,allowDelete)))}
function renderHistory(){const items=filtered(state.history);renderRecords(refs.history,refs.historyMeta,items,state.history.length,"registros",true)}
function renderFavorites(){const items=filtered(state.favorites);renderRecords(refs.favorites,refs.favoritesMeta,items,state.favorites.length,"favoritos",false)}
function normalizeExpression(expression){return expression.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-").replaceAll("√(","sqrt(").replaceAll("sen(","sin(").replaceAll("π","pi")}
function useRecord(expression,result){state.expression=normalizeExpression(expression);state.result=result;state.justCalculated=false;setStatus("");render()}
function memoryValue(){if(state.expression&&!state.justCalculated){try{return engine.evaluate(state.expression,{angleMode:state.settings.angleMode,ans:Number(state.ans)||0})}catch{}}return Number(state.result)||0}
function memory(type){const value=memoryValue();if(type==="clear")state.memory=0;else if(type==="recall"){state.expression=engine.formatResult(state.memory);state.justCalculated=false}else if(type==="add")state.memory+=value;else if(type==="subtract")state.memory-=value;render()}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=560;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.05);setTimeout(()=>c.close?.(),80)}catch{}}
function exportData(){const payload={app:"Calculator",version:"4.1",exportedAt:new Date().toISOString(),snapshot:store.snapshot()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="calculator-backup.json";a.click();URL.revokeObjectURL(url);toast("Dados exportados.")}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);store.importSnapshot(data.snapshot||data);state.history=store.loadHistory();state.favorites=store.loadFavorites();state.settings=store.loadSettings();toast("Dados importados.");render()}catch(err){toast(err instanceof Error?err.message:"Arquivo inválido.")}};reader.onerror=()=>toast("Não foi possível ler o arquivo.");reader.readAsText(file)}
function openHelp(){if(refs.help.showModal)refs.help.showModal();else refs.help.setAttribute("open","")}
function closeHelp(){if(refs.help.close)refs.help.close();else refs.help.removeAttribute("open")}
function action(type){if(type==="clear")return clearAll();if(type==="backspace"){if(state.justCalculated)return clearAll();state.expression=state.expression.slice(0,-1);render();return}if(type==="toggle-sign")return toggleSign();if(type==="equals")return calculate();if(type==="square")return square();if(type==="inverse")return inverse();if(type==="ans")return insertAns();if(type==="open-paren")return insert("(");if(type==="close-paren")return insert(")");if(type==="factorial")return insert("!")}
refs.keypad.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const d=b.dataset;if(d.number!==undefined)insert(d.number);else if(d.operation!==undefined)insert(d.operation);else if(d.functionName)insert(d.functionName,"function");else if(d.action)action(d.action)});
refs.memoryButtons.addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(!b)return;const t=b.dataset.action;memory(t==="memory-clear"?"clear":t==="memory-recall"?"recall":t==="memory-add"?"add":"subtract")});
[refs.history,refs.favorites].forEach(list=>list.addEventListener("click",e=>{const t=e.target.closest("button");if(!t)return;const a=t.dataset.action;if(a==="favorite")toggleFavorite(t.dataset.expression,t.dataset.result);else if(a==="copy")copyText(t.dataset.result,"Resultado");else if(a==="delete")removeHistory(t.dataset.id);else if(t.classList.contains("record__main"))useRecord(t.dataset.expression,t.dataset.result)}));
refs.clearHistory.addEventListener("click",clearHistory);refs.copy.addEventListener("click",()=>copyText(state.result,"Resultado"));refs.copyExpression.addEventListener("click",()=>copyText(state.expression||"0","Expressão"));
refs.tabs.forEach(t=>t.addEventListener("click",()=>{state.panel=t.dataset.panel;renderPanels()}));refs.search.addEventListener("input",e=>{state.search=e.target.value;renderHistory();renderFavorites()});
refs.angle.addEventListener("change",()=>{state.settings.angleMode=refs.angle.value;store.saveSettings(state.settings);render()});refs.theme.addEventListener("change",()=>{state.settings.theme=refs.theme.value;applySettings()});refs.style.addEventListener("change",()=>{state.settings.style=refs.style.value;applySettings()});refs.large.addEventListener("change",()=>{state.settings.largeText=refs.large.checked;applySettings()});refs.sound.addEventListener("change",()=>{state.settings.sound=refs.sound.checked;applySettings()});refs.animations.addEventListener("change",()=>{state.settings.animations=refs.animations.checked;applySettings()});refs.reset.addEventListener("click",()=>{state.settings={...defaults};applySettings();toast("Configurações restauradas.")});
refs.exportData.addEventListener("click",exportData);refs.importData.addEventListener("click",()=>refs.importFile.click());refs.importFile.addEventListener("change",e=>{const file=e.target.files?.[0];if(file)importData(file);e.target.value=""});
refs.helpButton.addEventListener("click",openHelp);refs.closeHelp.addEventListener("click",closeHelp);refs.help.addEventListener("click",e=>{if(e.target===refs.help)closeHelp()});
document.addEventListener("keydown",e=>{
 if(e.target.matches("input,select,textarea"))return;
 if(refs.help.open&&e.key==="Escape"){e.preventDefault();closeHelp();return}
 if(e.key==="?"||e.key==="F1"){e.preventDefault();openHelp();return}
 const k=e.key;if(/^\d$/.test(k)){e.preventDefault();insert(k);return}if(k==="."||k===","){e.preventDefault();insert(".");return}if("+-*/^%".includes(k)||k==="("||k===")"||k==="!"){e.preventDefault();insert(k);return}if(k==="Enter"||k==="="){e.preventDefault();calculate();return}if(k==="Backspace"){e.preventDefault();action("backspace");return}if(k==="Escape"||k.toLowerCase()==="c"){e.preventDefault();clearAll();return}if(k.toLowerCase()==="m"){e.preventDefault();memory("add");return}if(k.toLowerCase()==="r"){e.preventDefault();memory("recall");return}if(k.toLowerCase()==="d"){e.preventDefault();memory("clear");return}if(k.toLowerCase()==="a"){e.preventDefault();insertAns()}
});
render();if("serviceWorker"in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();